/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Capa1_Presentacion;

import java.awt.Dimension;

/**
 *
 * @author marie
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
        this.setExtendedState(frmMenu.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenuItem();
        menuTrabajadores = new javax.swing.JMenuItem();
        menuProductos = new javax.swing.JMenuItem();
        mnuFacturasVenta = new javax.swing.JMenuItem();
        mnuDetalleVentas = new javax.swing.JMenuItem();
        mnuFacturasCompra = new javax.swing.JMenuItem();
        mnuDetalleCompra = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        jMenu1.setText("Veterinaria");

        mnuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuClientes.setText("Clientes");
        mnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientesActionPerformed(evt);
            }
        });
        jMenu1.add(mnuClientes);

        menuTrabajadores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuTrabajadores.setText("Trabajadores");
        menuTrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTrabajadoresActionPerformed(evt);
            }
        });
        jMenu1.add(menuTrabajadores);

        menuProductos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuProductos.setText("Productos");
        menuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosActionPerformed(evt);
            }
        });
        jMenu1.add(menuProductos);

        mnuFacturasVenta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuFacturasVenta.setText("Facturas Venta");
        mnuFacturasVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFacturasVentaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuFacturasVenta);

        mnuDetalleVentas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuDetalleVentas.setText("Detalle Ventas");
        mnuDetalleVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDetalleVentasActionPerformed(evt);
            }
        });
        jMenu1.add(mnuDetalleVentas);

        mnuFacturasCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuFacturasCompra.setText("Facturas Compra");
        mnuFacturasCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFacturasCompraActionPerformed(evt);
            }
        });
        jMenu1.add(mnuFacturasCompra);

        mnuDetalleCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnuDetalleCompra.setText("Detalle Compra");
        jMenu1.add(mnuDetalleCompra);

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed
        frmClientes frm = new frmClientes();
        escritorio.add(frm);
        // CERRAR EL FORMUKARIO INTERNO
        
        //Tamaño de la ventana contenedor
        Dimension sizeContenedor = escritorio.getSize();
        //tamaño de la ventana clientes
        Dimension sizeFrmClientes = frm.getSize();
        
        frm.setLocation(((int)sizeContenedor.getWidth()- (int)sizeFrmClientes.getWidth())/2,
                ((int)sizeContenedor.getHeight() - (int)sizeFrmClientes.getHeight())/2);
        
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuClientesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    //llamar frmTrabajador 
    private void menuTrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTrabajadoresActionPerformed
       frmTrabajador frm = new frmTrabajador();
        escritorio.add(frm);
        // CERRAR EL FORMUKARIO INTERNO
        
        //Tamaño de la ventana contenedor
        Dimension sizeContenedor = escritorio.getSize();
        //tamaño de la ventana clientes
        Dimension sizeFrmTrabajador = frm.getSize();
        
        frm.setLocation(((int)sizeContenedor.getWidth()- (int)sizeFrmTrabajador.getWidth())/2,
                ((int)sizeContenedor.getHeight() - (int)sizeFrmTrabajador.getHeight())/2);
        
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_menuTrabajadoresActionPerformed

    private void menuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosActionPerformed
        frmProductos frm = new frmProductos();
        escritorio.add(frm);
        // CERRAR EL FORMUKARIO INTERNO
        
        //Tamaño de la ventana contenedor
        Dimension sizeContenedor = escritorio.getSize();
        //tamaño de la ventana clientes
        Dimension sizeFrmProductos = frm.getSize();
        
        frm.setLocation(((int)sizeContenedor.getWidth()- (int)sizeFrmProductos.getWidth())/2,
                ((int)sizeContenedor.getHeight() - (int)sizeFrmProductos.getHeight())/2);
        
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_menuProductosActionPerformed

    private void mnuFacturasCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFacturasCompraActionPerformed
       frmFactura_Compra frm = new frmFactura_Compra();
        escritorio.add(frm);
        // CERRAR EL FORMUKARIO INTERNO
        
        //Tamaño de la ventana contenedor
        Dimension sizeContenedor = escritorio.getSize();
        //tamaño de la ventana clientes
        Dimension sizefrmFactura_Compra = frm.getSize();
        
        frm.setLocation(((int)sizeContenedor.getWidth()- (int)sizefrmFactura_Compra.getWidth())/2,
                ((int)sizeContenedor.getHeight() - (int)sizefrmFactura_Compra.getHeight())/2);
        
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuFacturasCompraActionPerformed

    private void mnuFacturasVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFacturasVentaActionPerformed
        frmFactura_Venta frm = new frmFactura_Venta();
        escritorio.add(frm);
        // CERRAR EL FORMUKARIO INTERNO
        
        //Tamaño de la ventana contenedor
        Dimension sizeContenedor = escritorio.getSize();
        //tamaño de la ventana clientes
        Dimension sizefrmFactura_Venta = frm.getSize();
        
        frm.setLocation(((int)sizeContenedor.getWidth()- (int)sizefrmFactura_Venta.getWidth())/2,
                ((int)sizeContenedor.getHeight() - (int)sizefrmFactura_Venta.getHeight())/2);
        
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuFacturasVentaActionPerformed

    private void mnuDetalleVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDetalleVentasActionPerformed
        frmDetalle_Ventas frm = new frmDetalle_Ventas();
        escritorio.add(frm);
        // CERRAR EL FORMUKARIO INTERNO
        
        //Tamaño de la ventana contenedor
        Dimension sizeContenedor = escritorio.getSize();
        //tamaño de la ventana clientes
        Dimension sizefrmDetalle_Ventas = frm.getSize();
        
        frm.setLocation(((int)sizeContenedor.getWidth()- (int)sizefrmDetalle_Ventas.getWidth())/2,
                ((int)sizeContenedor.getHeight() - (int)sizefrmDetalle_Ventas.getHeight())/2);
        
        frm.toFront();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuDetalleVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuProductos;
    private javax.swing.JMenuItem menuTrabajadores;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenuItem mnuDetalleCompra;
    private javax.swing.JMenuItem mnuDetalleVentas;
    private javax.swing.JMenuItem mnuFacturasCompra;
    private javax.swing.JMenuItem mnuFacturasVenta;
    // End of variables declaration//GEN-END:variables
}
