--Mariel Daniela Rojas Sánchez

CREATE DATABASE VETERINARIA
GO

USE VETERINARIA
GO

--DROP DATABASE  VETERINARIA

CREATE TABLE CLIENTE(
	ID_CLIENTE VARCHAR(15) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(80) NOT NULL,
	APELLIDO VARCHAR(80) NOT NULL,
	TELEFONO VARCHAR(11) NULL,
	EMAIL  VARCHAR(45) NOT NULL,
)
GO

-- tabla veterinario
CREATE TABLE VETERINARIO(
	ID_VETERINARIO VARCHAR(15) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(80) NOT NULL,
	APELLIDO VARCHAR(80) NOT NULL,
	TELEFONO VARCHAR(11) NULL,
	EMAIL  VARCHAR(45) NOT NULL,
	ESPECIALIDAD VARCHAR(35) NOT NULL DEFAULT ('GENERAL')
)
GO

-- tabla secretaria
CREATE TABLE SECRETARIA(
	ID_SECRETIARIA VARCHAR(15) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(80) NOT NULL,
	APELLIDO VARCHAR(80) NOT NULL,
	TELEFONO VARCHAR(11) NULL,
	EMAIL  VARCHAR(45) NOT NULL,
)
GO

-- Crear la tabla de Mascotas
CREATE TABLE MASCOTA (
    ID_MASCOTA INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100),
    ESPECIE VARCHAR(50),
    RAZA VARCHAR(50),
    FECHA_NACIMIENTI DATE,
    ID_CLIENTE VARCHAR(15) NOT NULL FOREIGN KEY REFERENCES CLIENTE(ID_CLIENTE) -- llave foranea
);

-- Historial Medicos
CREATE TABLE HISTORIAL_MEDICO (
	ID_HISTORIAL INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_MASCOTA INT NOT NULL FOREIGN KEY REFERENCES MASCOTA(ID_MASCOTA),
    ID_VETERINARIO VARCHAR(15) NOT NULL FOREIGN KEY REFERENCES VETERINARIO(ID_VETERINARIO),
    DESCRIPCION VARCHAR(200) NOT NULL,
    FECHA DATE NOT NULL
);

--  Facturas compra
CREATE TABLE FACTURA_COMPRA (
    NUM_FACTURA INT IDENTITY(1,1) PRIMARY KEY,
	TOTAL DECIMAL(10, 2) NOT NULL, 
    FECHA DATE NOT NULL,
	ESTADO VARCHAR(10),
	PROVEEDOR VARCHAR(65) NOT NULL
);

--  Facturas venta
CREATE TABLE FACTURA_VENTA (
    NUM_FACTURA INT IDENTITY(1,1) PRIMARY KEY,
    ID_CLIENTE VARCHAR(15) NOT NULL FOREIGN KEY REFERENCES CLIENTE(ID_CLIENTE), -- llave foranea
	TOTAL DECIMAL(10, 2) NOT NULL, 
    FECHA DATE NOT NULL,
	ESTADO VARCHAR(10),
	METODO_PAGO VARCHAR(10) CONSTRAINT CHK_METODOPAGO
        CHECK (METODO_PAGO IN ('Sinpe', 'Efectivo', 'Tarjeta'))

);


--Producto
CREATE TABLE PRODUCTO(
    ID_PRODUCTO INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    PRECIO DECIMAL(10, 2) NOT NULL,
    CANTIDAD_DISPONIBLE INT NOT NULL,
	FECHA_VENCIMINETO DATE,
	CATEGORIA VARCHAR(25)
);


--DetalleFactura venta
CREATE TABLE DETALLE_FACTURA_VENTA (
    ID_DETALLE INT IDENTITY(1,1) PRIMARY KEY,
	NUM_FACTURA INT FOREIGN KEY REFERENCES FACTURA_VENTA(NUM_FACTURA),
	ID_PRODUCTO INT FOREIGN KEY REFERENCES PRODUCTO(ID_PRODUCTO),
    CANTIDAD INT NOT NULL,
    PRECIO_VENTA DECIMAL(10, 2) NOT NULL,
    SUBTOTAL DECIMAL(10, 2) NOT NULL,
);


--DetalleFactura compra
CREATE TABLE DETALLE_FACTURA_COMPRA (
    ID_DETALLE INT IDENTITY(1,1) PRIMARY KEY,
	NUM_FACTURA INT FOREIGN KEY REFERENCES FACTURA_COMPRA(NUM_FACTURA),
	ID_PRODUCTO INT FOREIGN KEY REFERENCES PRODUCTO(ID_PRODUCTO),
    CANTIDAD INT NOT NULL,
	PRECIO_COMPRA DECIMAL(10, 2) NOT NULL,
    SUBTOTAL DECIMAL(10, 2) NOT NULL,
);

-- procedimientos almacenados, scrud, CLIENTE, VETERINBARIO, SECRETARIO, HISTORIAL, FASCTURAS, DETALLES

GO
CREATE PROCEDURE ELIMINAR
		@idcliente int,  --recibe un id
		@msj varchar(50) out   --devuelve un mensaje
AS BEGIN
if (not exists(select * from CLIENTE where ID_cliente=@idcliente))
	begin
		set @msj='El cliente no existe'
		return 0
	end
else
	begin
		DELETE from CLIENTE where ID_cliente=@idcliente
		set @msj='cliente eliminado'
		return 1
	end
END
GO

--hacer inner join de las tabla mascota y cliente, para saber el nombre del dueño de la mascota
